name: Deploy to Render

on:
  push:
    branches:
      - main  # This will trigger the workflow when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Render
        uses: render-examples/github-actions-render@v1
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }}

      - name: Build and Deploy to Render
        run: |
          docker build -t my-app .
          docker push my-app
          render deploy --service my-app
