name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deploy when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub will run this job on an Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out your repository so GitHub Actions can access it

      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-csp3r423esus73bfrno0?key=SNtz_xOtzBU
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Use GitHub Secrets to store sensitive data securely
