name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository so GitHub Actions can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building images

      - name: Login to Render
        uses: render-examples/github-actions-render@v1  # Login to Render using your API key
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }}

      - name: Build and Deploy to Render
        run: |
          docker build -t portfolio-website .  # Build the Docker image from your Dockerfile
          render deploy --service portfolio-website-1  # Deploy directly to Render; replace with your actual Service ID if necessary
